-- 코드를 입력하세요
SELECT DISTINCT CAR_ID, CAR_TYPE, FEE
FROM
(SELECT CAR.CAR_ID, CAR.CAR_TYPE, TRUNCATE(DAILY_FEE *30 * (1 - 0.01 * DISCOUNT_RATE), 0) FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS ON CAR.CAR_ID = HIS.CAR_ID
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PL ON CAR.CAR_TYPE = PL.CAR_TYPE
WHERE CAR.CAR_ID NOT IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE END_DATE >= '2022-11-01' AND START_DATE < '2022-12-01')
AND PL.DURATION_TYPE = '30일 이상'
AND CAR.CAR_TYPE IN ('SUV', '세단')
) A
WHERE (FEE >= 500000 AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC