-- 코드를 입력하세요
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG_SCORE, 2)
FROM
(SELECT RI.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, AVG(REVIEW_SCORE) AVG_SCORE
FROM REST_INFO RI INNER JOIN REST_REVIEW RR ON RI.REST_ID = RR.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_NAME
) A
ORDER BY 6 DESC, 4 DESC