-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(1)
FROM
(SELECT DATE_FORMAT(SALES_DATE, '%Y') YEAR,
       DATE_FORMAT(SALES_DATE, '%m') MONTH,
       GENDER,
       OS.USER_ID
FROM USER_INFO UI RIGHT JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
GROUP BY 1, 2, 3, 4
ORDER BY 1, 2, 3
) A
WHERE GENDER IS NOT NULL
GROUP BY 1, 2, 3
