-- 코드를 입력하세요
SELECT YEAR, MONTH, GENDER, COUNT(1,2,3)
FROM
(SELECT DATE_FORMAT(SALES_DATE, '%Y') YEAR,
       DATE_FORMAT(SALES_DATE, '%m') MONTH,
       GENDER
FROM USER_INFO UI RIGHT JOIN ONLINE_SALE OS ON UI.USER_ID = OS.USER_ID
) A
GROUP BY YEAR, MONTH, GENDER
ORDER BY 1, 2, 3