-- 코드를 입력하세요
SELECT YEAR(SALES_DATE), MONTH(SALES_DATE), COUNT(DISTINCT INFO.USER_ID),
       ROUND(COUNT(DISTINCT INFO.USER_ID) / (SELECT COUNT(USER_ID) FROM USER_INFO INFO WHERE YEAR(JOINED) = '2021'), 1)
FROM USER_INFO INFO INNER JOIN ONLINE_SALE SALE ON INFO.USER_ID = SALE.USER_ID
WHERE YEAR(JOINED) = '2021'
GROUP BY 1, 2
ORDER BY 1, 2