-- 코드를 입력하세요
SELECT FO.PRODUCT_ID, PRODUCT_NAME, SUM(PRICE*AMOUNT)
FROM FOOD_PRODUCT FP INNER JOIN FOOD_ORDER FO ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE DATE_FORMAT(PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID
ORDER BY SUM(PRICE*AMOUNT) DESC, FO.PRODUCT_ID