-- 코드를 입력하세요
WITH RENT AS (SELECT HISTORY_ID, HIS.CAR_ID, DATEDIFF(END_DATE, START_DATE) + 1 DURATION,
        CASE WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
             WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상' END DURATION_TYPE,
        CAR_TYPE, DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CAR.CAR_ID = HIS.CAR_ID
WHERE CAR_TYPE = '트럭')

SELECT HISTORY_ID, TRUNCATE(DAILY_FEE * DURATION * (1 - 0.01 * COALESCE(DISCOUNT_RATE, 0)), 0) FEE
FROM RENT LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PL ON RENT.CAR_TYPE = PL.CAR_TYPE
AND RENT.DURATION_TYPE = PL.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC