-- 코드를 입력하세요
SELECT FH.FLAVOR
FROM FIRST_HALF FH INNER JOIN ICECREAM_INFO II ON FH.FLAVOR = II.FLAVOR
WHERE INGREDIENT_TYPE = 'fruit_based'
AND TOTAL_ORDER > 3000
GROUP BY FH.FLAVOR
ORDER BY TOTAL_ORDER DESC