-- 코드를 입력하세요
SELECT DISTINCT HIS.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HIS ON CAR.CAR_ID = HIS.CAR_ID
WHERE DATE_FORMAT(START_DATE, '%m') = '10'
AND CAR_TYPE = '세단'
ORDER BY HIS.CAR_ID DESC