-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',UGB.BOARD_ID,'/',FILE_ID,FILE_NAME,FILE_EXT) FILE_PATH
FROM USED_GOODS_BOARD UGB LEFT JOIN USED_GOODS_FILE UGF ON UGB.BOARD_ID = UGF.BOARD_ID
WHERE VIEWS IN (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)