-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM
(SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK () OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) RANKING
FROM FOOD_PRODUCT
WHERE CATEGORY REGEXP '과자|국|김치|식용유'
) A
WHERE RANKING = 1
ORDER BY PRICE DESC